/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_example_combosample_GLRenderer */

#ifndef _Included_com_google_example_combosample_GLRenderer
#define _Included_com_google_example_combosample_GLRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_example_combosample_GLRenderer
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_GLRenderer_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_GLRenderer
 * Method:    nativeOnSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_GLRenderer_nativeOnSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_GLRenderer
 * Method:    nativeOnSurfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_GLRenderer_nativeOnSurfaceChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_GLRenderer
 * Method:    nativeOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_GLRenderer_nativeOnDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_GLRenderer
 * Method:    nativeOnUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_GLRenderer_nativeOnUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
