/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_example_combosample_MainActivity */

#ifndef _Included_com_google_example_combosample_MainActivity
#define _Included_com_google_example_combosample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_example_combosample_MainActivity_MODE_PRIVATE
#define com_google_example_combosample_MainActivity_MODE_PRIVATE 0L
#undef com_google_example_combosample_MainActivity_MODE_WORLD_READABLE
#define com_google_example_combosample_MainActivity_MODE_WORLD_READABLE 1L
#undef com_google_example_combosample_MainActivity_MODE_WORLD_WRITEABLE
#define com_google_example_combosample_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_google_example_combosample_MainActivity_MODE_APPEND
#define com_google_example_combosample_MainActivity_MODE_APPEND 32768L
#undef com_google_example_combosample_MainActivity_BIND_AUTO_CREATE
#define com_google_example_combosample_MainActivity_BIND_AUTO_CREATE 1L
#undef com_google_example_combosample_MainActivity_BIND_DEBUG_UNBIND
#define com_google_example_combosample_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_google_example_combosample_MainActivity_BIND_NOT_FOREGROUND
#define com_google_example_combosample_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_google_example_combosample_MainActivity_CONTEXT_INCLUDE_CODE
#define com_google_example_combosample_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_google_example_combosample_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_google_example_combosample_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_google_example_combosample_MainActivity_CONTEXT_RESTRICTED
#define com_google_example_combosample_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_google_example_combosample_MainActivity_RESULT_CANCELED
#define com_google_example_combosample_MainActivity_RESULT_CANCELED 0L
#undef com_google_example_combosample_MainActivity_RESULT_OK
#define com_google_example_combosample_MainActivity_RESULT_OK -1L
#undef com_google_example_combosample_MainActivity_RESULT_FIRST_USER
#define com_google_example_combosample_MainActivity_RESULT_FIRST_USER 1L
#undef com_google_example_combosample_MainActivity_DEFAULT_KEYS_DISABLE
#define com_google_example_combosample_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_google_example_combosample_MainActivity_DEFAULT_KEYS_DIALER
#define com_google_example_combosample_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_google_example_combosample_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_google_example_combosample_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_google_example_combosample_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_google_example_combosample_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_google_example_combosample_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_google_example_combosample_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    signIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_signIn
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    signOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_signOut
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    showAchievements
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_showAchievements
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    showLeaderboards
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_showLeaderboards
  (JNIEnv *, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    nativeOnActivityCreated
 * Signature: (Landroid/app/Activity;Landroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_nativeOnActivityCreated
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    nativeOnActivityResult
 * Signature: (Landroid/app/Activity;IILandroid/content/Intent;)V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_nativeOnActivityResult
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_google_example_combosample_MainActivity
 * Method:    setAuthResultCallback
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_google_example_combosample_MainActivity_setAuthResultCallback
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
